INSERT INTO public.shipping_zones
(name_ar, name_en, shipping_price, free_shipping_threshold, estimated_delivery, is_active)
VALUES
('القاهرة', 'Cairo', 0, NULL, '2 - 4 أيام', true),
('الجيزة', 'Giza', 0, NULL, '2 - 4 أيام', true),
('الإسكندرية', 'Alexandria', 0, NULL, '2 - 4 أيام', true),
('القليوبية', 'Qalyubia', 0, NULL, '2 - 4 أيام', true),
('الدقهلية', 'Dakahlia', 0, NULL, '2 - 4 أيام', true),
('البحر الأحمر', 'Red Sea', 0, NULL, '3 - 5 أيام', true),
('البحيرة', 'Beheira', 0, NULL, '2 - 4 أيام', true),
('الفيوم', 'Faiyum', 0, NULL, '2 - 4 أيام', true),
('الغربية', 'Gharbia', 0, NULL, '2 - 4 أيام', true),
('الإسماعيلية', 'Ismailia', 0, NULL, '2 - 4 أيام', true),
('المنوفية', 'Monufia', 0, NULL, '2 - 4 أيام', true),
('المنيا', 'Minya', 0, NULL, '3 - 5 أيام', true),
('الوادي الجديد', 'New Valley', 0, NULL, '4 - 6 أيام', true),
('شمال سيناء', 'North Sinai', 0, NULL, '4 - 6 أيام', true),
('بورسعيد', 'Port Said', 0, NULL, '2 - 4 أيام', true),
('دمياط', 'Damietta', 0, NULL, '2 - 4 أيام', true),
('الشرقية', 'Sharqia', 0, NULL, '2 - 4 أيام', true),
('جنوب سيناء', 'South Sinai', 0, NULL, '4 - 6 أيام', true),
('كفر الشيخ', 'Kafr El Sheikh', 0, NULL, '2 - 4 أيام', true),
('مطروح', 'Matrouh', 0, NULL, '4 - 6 أيام', true),
('الأقصر', 'Luxor', 0, NULL, '4 - 6 أيام', true),
('قنا', 'Qena', 0, NULL, '4 - 6 أيام', true),
('سوهاج', 'Sohag', 0, NULL, '4 - 6 أيام', true),
('بني سويف', 'Beni Suef', 0, NULL, '3 - 5 أيام', true),
('أسيوط', 'Assiut', 0, NULL, '4 - 6 أيام', true),
('أسوان', 'Aswan', 0, NULL, '5 - 7 أيام', true);
